import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'




export default function Home() {
  return (
    <div className={styles.container}>


      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>



      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='myspan dummy'>

           Hunting Coder
          </span>
        </h1>


        <p className={styles.description}>
         A blog  for hunting coders by a hunting coders Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit inventore debitis accusamus error, omnis provident tempora. Aperiam ea, praesentium, maiores illo eius culpa dignissimos quibusdam porro doloremque vel nihil optio.
        </p>


<h2>Popular Tags</h2>
        <div className="blog">
          <div className='blogItems'>
            <h3> How to learn Javascript in 2022</h3>
            <p> Javascript is a language used to design logic for the web</p>
          </div>
        </div>
        <div className='blog'>
          <div className='blogItems'>
            <h3> How to learn Javascript in 2022</h3>
            <p> Javascript is a language used to design logic for the web</p>
          </div>
        </div>
        <div className='blog'>
          <div className='blogItems'>
            <h3> How to learn Javascript in 2022</h3>
            <p> Javascript is a language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            {/* <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
